### PR TITLE
Translation system improvement and extra translation

### PR DESCRIPTION
**Pull request by Blueberryy**
Moved cl_language.lua to gmod localization files

### CODE REVIEW

**Comment by JShorthouse** [comment]
Thanks for the patch Blueberryy, very much appreciated.
I don't have gmod installed to test right now but I will trust you that it is working.

Just a couple of suggested improvements before I merge in:

- If `cl_language.lua` is no longer used could you please remove this file? The two references to it in `autorun/server/easydoorbell_sv_init.lua` and `autorun/client/easydoorbell_cl_init.lua` can then be removed too.
- Github is showing a few files without terminating newlines, could you please add these?

Thanks

**Comment by Blueberryy** [comment]
Yeah it works perfectly.

**Comment by Blueberryy** [comment]
And i just cleaned that code with cl_language.lua from easydoorbell_sv_init.lua and easydoorbell_cl_init.lua

**Comment by JShorthouse** [comment]
Alright great!

Could you please delete the `cl_language.lua` file and add newlines to the end of both of the localization files, and then I will be happy to merge this in.

**Comment by Blueberryy** [comment]
Ok i did it

**Comment by JShorthouse** [comment]
Ok thanks, if you can also add newlines to the end of both the localization files like I mentioned earlier then I will merge this in.

**Comment by Blueberryy** [comment]
File work without newlines. Why you neee it?

**Comment by JShorthouse** [comment]
For consistency with all of the other files in this repo and because it's part of the Unix standard. Linux and MacOS expect files to be newline terminated.

See:
https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline

**Comment by Blueberryy** [comment]
will try

**Comment by Blueberryy** [comment]
Done

**Comment by JShorthouse** [comment]
Thanks very much, merged!

I will update the readme to give you credit.

**Pull request merged**
